Logger save
marcinwozniak0/BakcylProgramowania_2020 pull request #17
Opened 2021-01-22 10:26 UTC by wiktorszewczyk

2021-01-24 16:58 UTC, marcinwozniak0 requested changes

2021-01-24 16:58 UTC, marcinwozniak0 commented on Logger/Logger.cpp
> +    time_t     now = time(0);
wole formatowanie bez tych wielu spacji. Po prostu time_t now = time(0)

2021-01-24 16:58 UTC, marcinwozniak0 commented on Logger/Logger.cpp
> +#include <stdio.h>
<cstdio>

2021-01-24 16:58 UTC, marcinwozniak0 commented on Logger/Logger.cpp
> +#include <time.h>
<ctime>

2021-01-25 09:51 UTC, marcinwozniak0 commented
@wiktorszewczyk jest okej, musisz tylko jeszcze rozwiązać konflikty, żeby można było robić merge do maina
![image](https://user-images.githubusercontent.com/36385922/105689631-49a0a880-5efb-11eb-904d-a5abe1c41891.png)

2021-01-25 11:18 UTC, wiktorszewczyk commented
@marcinwozniak0 w jaki sposób mam rozwiązać te konflikty? Przy wybraniu Merge pull request nie ma konfliktów bo rozwiązywałem je wcześniej, a przy wybraniu opcji Rebase and merge, nie mam nigdzie opcji Resolve conflicts

2021-01-25 15:34 UTC, marcinwozniak0 commented
To kliknij w to 
![image](https://user-images.githubusercontent.com/36385922/105727189-1f66df00-5f2b-11eb-99e7-dbcf116d4865.png)

i potem przepisz w swoim terminalu te instrukcje, które się pojawily

2021-01-25 16:05 UTC, wiktorszewczyk commented
@marcinwozniak0 coś zepsułem i się źle wysłało, ale już poprawiłem w kodzie bezpośrednio na mainie

2021-01-25 16:05 UTC, closed without merging